spring:
  application:
    name: calendar
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: homates.exchange
    queue: homates.calendar.queue
    routingkey: homates.calendar

server:
  port: 8084
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
