spring:org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role
  application:
    name: user-houses
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: homates.exchange
    routingkeyboard: homates.board
    routingkeywallet: homates.wallet
    routingkeyshopl: homates.shopl
    routingkeycalendar: homates.calendar

server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
