spring:
  application:
    name: user-houses
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: homates.topic
    routingkey: homates.delhouse.any
    routingkeyboard: homates.delhouse.board
    routingkeywallet: homates.delhouse.wallet
    routingkeyshopl: homates.delhouse.shopl

server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
