version: "1"

services:

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    image: ivsnp/homates-eureka:1.0.0
    ports:
      - 8761:8761
    networks:
      - homatesnet
    restart: on-failure

  api-gateway:
    build: api-gateway
    container_name: api-gateway
    image: ivsnp/homates-apigateway:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - eureka-service
    networks:
      - homatesnet
    restart: on-failure

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - homatesnet
    restart: on-failure

  # DBs

  user-houses-postgres:
    container_name: user-houses-postgres
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - homates-user-houses-data:/var/lib/postgresql/data
    networks:
      - homatesnet
    environment:
      POSTGRES_DB: homates-user-houses
      POSTGRES_USER: homates
      POSTGRES_PASSWORD: admin
      restart: always

  wallet-postgres:
    container_name: wallet-postgres
    image: postgres:latest
    ports:
      - 5434:5432
    volumes:
      - homates-wallet-data:/var/lib/postgresql/data
    networks:
      - homatesnet
    environment:
      POSTGRES_DB: homates-wallet
      POSTGRES_USER: homates
      POSTGRES_PASSWORD: admin
      restart: always

  shopping-list-postgres:
    container_name: shopping-list-postgres
    image: postgres:latest
    ports:
      - 5435:5432
    volumes:
      - homates-shopping-list-data:/var/lib/postgresql/data
    networks:
      - homatesnet
    environment:
      POSTGRES_DB: homates-shopping-list
      POSTGRES_USER: homates
      POSTGRES_PASSWORD: admin
      restart: always

  board-postgres:
    container_name: board-postgres
    image: postgres:latest
    ports:
      - 5436:5432
    volumes:
      - homates-board-data:/var/lib/postgresql/data
    networks:
      - homatesnet
    environment:
      POSTGRES_DB: homates-board
      POSTGRES_USER: homates
      POSTGRES_PASSWORD: admin
      restart: always

  calendar-postgres:
    container_name: calendar-postgres
    image: postgres:latest
    ports:
      - 5437:5432
    volumes:
      - homates-calendar-data:/var/lib/postgresql/data
    networks:
      - homatesnet
    environment:
      POSTGRES_DB: homates-calendar
      POSTGRES_USER: homates
      POSTGRES_PASSWORD: admin
      restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: homates@homates.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 50
    ports:
      - 5050:50
    volumes:
      - homates-pgadmin-data:/var/lib/pgadmin
    depends_on:
      - user-houses-postgres
      - wallet-postgres
      - shopping-list-postgres
      - board-postgres
      - calendar-postgres
    networks:
      - homatesnet

  # APP microservices

  react-desktop:
    build: ./react
    container_name: react-desktop
    image: react-desktop:latest
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    networks:
      - homatesnet
    deploy:
      restart_policy:
        condition: on-failure

  user-houses:
    build: user-houses
    container_name: user-houses
    image: ivsnp/homates-userhouses:1.0.0
    ports:
      - 8081:8081
    networks:
      - homatesnet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-houses-postgres:5432/homates-user-houses
      - SPRING_DATASOURCE_USERNAME=homates
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - eureka-service
      - user-houses-postgres

  wallet:
    build: wallet
    container_name: wallet
    image: ivsnp/homates-wallet:1.0.0
    ports:
      - 8082:8082
    networks:
      - homatesnet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-postgres:5432/homates-wallet
      - SPRING_DATASOURCE_USERNAME=homates
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - eureka-service
      - wallet-postgres

  shopping-list:
    build: shopping-list
    container_name: shopping-list
    image: ivsnp/homates-shopl:1.0.0
    ports:
      - 8083:8083
    networks:
      - homatesnet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopping-list-postgres:5432/homates-shopping-list
      - SPRING_DATASOURCE_USERNAME=homates
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - eureka-service
      - shopping-list-postgres

  calendar:
    build: calendar
    container_name: calendar
    image: ivsnp/homates-calendar:1.0.0
    ports:
      - 8084:8084
    networks:
      - homatesnet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://calendar-postgres:5432/homates-calendar
      - SPRING_DATASOURCE_USERNAME=homates
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - eureka-service
      - calendar-postgres

  board:
    build: bacheca
    container_name: board
    image: ivsnp/homates-board:1.0.0
    ports:
      - 8085:8085
    networks:
      - homatesnet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://board-postgres:5432/homates-board
      - SPRING_DATASOURCE_USERNAME=homates
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - eureka-service
      - board-postgres

volumes:
  homates-pgadmin-data:
  homates-user-houses-data:
  homates-wallet-data:
  homates-shopping-list-data:
  homates-board-data:
  homates-calendar-data:
networks:
  homatesnet:
    driver: bridge

# --- HOW-TO ---
# 1. create .jar files
# 2. run on terminal in current folder: "docker compose build && docker compose up -d"