version: "1"

services:

  eureka-service:
    build: eureka-service
    container_name: eureka-service
    image: eurekaservice:latest
    ports:
      - 8761:8761
    networks:
      - homatesnet
    restart: on-failure

  api-gateway:
    build: api-gateway
    container_name: api-gateway
    image: api-gateway:latest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
    ports:
      - 8080:8080
    depends_on:
      - eureka-service
    networks:
      - homatesnet
    restart: on-failure

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - homatesnet
    restart: on-failure

  # DBs
  dbhomates-postgres:
    container_name: dbhomates-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/dbhomates-postgres/data
    networks:
      - homatesnet
    environment:
      POSTGRES_DB: dbhomates
      POSTGRES_USER: homates
      POSTGRES_PASSWORD: admin
      restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: homates@homates.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 50
    ports:
      - 5050:50
    volumes:
      - pgadmin-data:/pgadmin
    depends_on:
      - dbhomates-postgres
    networks:
      - homatesnet

  # APP microservices
  #accounting:
  #  build: accounting
  #  container_name: accounting
  #  image: accounting:latest
  #  ports:
  #    - 8081:8081
  #  depends_on:
  #    - eureka-service
  #  networks:
  #    - homatesnet
  #  environment:
  #    - SPRING_PROFILES_ACTIVE=docker
  #    - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
  #    - SPRING_DATASOURCE_URL=jdbc:postgresql://dbhomates-postgres:5432/dbhomates
  #    - SPRING_DATASOURCE_USERNAME=homates
  #    - SPRING_DATASOURCE_PASSWORD=admin
  #    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #  deploy:
  #    restart_policy:
  #      condition: on-failure

  shopping-list:
    build: shopping-list
    container_name: shopping-list
    image: shopping-list:latest
    ports:
      - 8082:8082
    depends_on:
      - eureka-service
    networks:
      - homatesnet
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbhomates-postgres:5432/dbhomates
      - SPRING_DATASOURCE_USERNAME=homates
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db-data:
  api-test:
  pgadmin-data:
networks:
  homatesnet:
    driver: bridge

# --- HOW-TO ---
# 1. create .jar files
# 2. run on terminal in current folder: "docker compose build && docker compose up -d"