server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: user-houses
            uri: lb://user-houses
            predicates:
              - Path=/api/v1/user-houses/**
        -   id: wallet
            uri: lb://wallet
            predicates:
              - Path=/api/v1/wallet/**
        -   id: shopping-list
            uri: lb://shopping-list
            predicates:
              - Path=/api/v1/shoppinglist/**
        -   id: bacheca
            uri: lb://bacheca
            predicates:
              - Path=/api/v1/bacheca/**
