server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            max-age: 3600
            allowed-headers: "Requestor-Type"
            exposed-headers: "X-Get-Header"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: user-houses
            uri: lb://user-houses
            predicates:
              - Path=/api/v1/user-houses/**
        -   id: wallet
            uri: lb://wallet
            predicates:
              - Path=/api/v1/wallet/**
        -   id: shopping-list
            uri: lb://shopping-list
            predicates:
              - Path=/api/v1/shoppinglist/**
        - id: calendar
          uri: lb://calendar
          predicates:
            - Path=/api/v1/calendar/**
        -   id: bacheca
            uri: lb://bacheca
            predicates:
              - Path=/api/v1/bacheca/**
