spring:
  application:
    name: bacheca
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: homates.topic
    queue: homates.board.queue
    routingkey: homates.delhouse.board

server:
  port: 8085
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka


