spring:
  application:
    name: bacheca
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

server:
  port: 8085
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka


