server:
    port: 8080
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}

spring:
    application:
        name: apigateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                -   id: listaspesa
                    uri: lb://listaspesa
                    predicates:
                    - Path=/api/v1/chefs/**