apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway  #nome deployment
spec:
  replicas: 1 #repliche dell'api-gateway in caso di rottura
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway #pod nel deployment
          image: mattialadisa/api-gateway:1.0.0
          imagePullPolicy: Always
          env:
             - name: EUREKA_DZ
               value: "http://eureka-service-0.eureka-service:8761/eureka"
          ports:
            - containerPort: 8080 #porta in cui esce il pod ossia il container
---
#file service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
      - port: 8080
        targetPort: 8080
  type: ClusterIP