apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopping-list-postgres  #nome deployment
spec:
  serviceName: shopping-list-postgres
  replicas: 1 #repliche dell'eureka-service in caso di rottura
  selector:
    matchLabels:
      app: shopping-list-postgres
  template:
    metadata:
      labels:
        app: shopping-list-postgres
    spec:
      containers:
        - name: shopping-list-postgres #pod nel deployment
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: "homates-shopping-list"
            - name: POSTGRES_USER
              value: "homates"
            - name: POSTGRES_PASSWORD
              value: "admin"
          ports:
            - containerPort: 5432 #porta in cui esce il pod ossia il container
---
#file service
apiVersion: v1
kind: Service
metadata:
  name: shopping-list-postgres
spec:
  clusterIP: None
  selector:
    app: shopping-list-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP