apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet  #nome deployment
spec:
  replicas: 1 #repliche dell'wallet in caso di rottura
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
        - name: wallet #pod nel deployment
          image: mattialadisa/wallet:1.0.0
          imagePullPolicy: Always
          env:
            - name: EUREKA_DZ
              value: "http://eureka-service-0.eureka-service:8761/eureka"
            - name: DB_CONNECTION
              value: "jdbc:postgresql://wallet-postgres.default.svc.cluster.local:5432/homates-wallet"
            - name: SPRING_DATASOURCE_USERNAME
              value: "homates"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbit.default.svc.cluster.local"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "admin"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "admin"

          ports:
            - containerPort: 8082 #porta in cui esce il pod ossia il container
---
#file service
apiVersion: v1
kind: Service
metadata:
  name: wallet
spec:
  selector:
    app: wallet
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP