# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calendar-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"

---
# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calendar-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
# deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: homates
  name: calendar-postgres  #nome deployment
spec:
  serviceName: calendar-postgres
  replicas: 1 #repliche dell'eureka-service in caso di rottura
  selector:
    matchLabels:
      app: calendar-postgres
  template:
    metadata:
      labels:
        app: calendar-postgres
    spec:
      volumes:
        - name: calendar-pv-storage
          persistentVolumeClaim:
            claimName: calendar-pv-claim
      containers:
        - name: calendar-postgres #pod nel deployment
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: "homates-calendar"
            - name: POSTGRES_USER
              value: "homates"
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432 #porta in cui esce il pod ossia il container
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"
---
# service
apiVersion: v1
kind: Service
metadata:
  namespace: homates
  name: calendar-postgres
spec:
  clusterIP: None
  selector:
    app: calendar-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP