# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: userhouses-pv-volume
  labels:
    app: user-houses-postgres
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data

---
# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userhouses-pv-claim
  labels:
    app: user-houses-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: homates
  name: user-houses-postgres  #nome deployment
  labels:
    app: user-houses-postgres
spec:
  serviceName: user-houses-postgres
  replicas: 1 #repliche dell'eureka-service in caso di rottura
  selector:
    matchLabels:
      app: user-houses-postgres
  template:
    metadata:
      labels:
        app: user-houses-postgres
    spec:
      containers:
        - name: user-houses-postgres #pod nel deployment
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: "homates-user-houses"
            - name: POSTGRES_USER
              value: "homates"
            - name: POSTGRES_PASSWORD
              value: "admin"
          ports:
            - containerPort: 5432 #porta in cui esce il pod ossia il container
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: userhouses-pv-storage
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"
      volumes:
        - name: userhouses-pv-storage
          persistentVolumeClaim:
            claimName: userhouses-pv-claim

---
# service
apiVersion: v1
kind: Service
metadata:
  namespace: homates
  name: user-houses-postgres
spec:
  clusterIP: None
  selector:
    app: user-houses-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP