spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 820097544051-kvp28gqbpj0948a4rquoan6v1p5fc34j.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: localhost:http://eureka-service:8761/eureka
