spring:
    oauth2:
      client:
        registration:
          google:
            clientId: 820097544051-kvp28gqbpj0948a4rquoan6v1p5fc34j.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8080/api/v1/oauth2/google/{registrationId}"
            scope:
              - email
              - profile

server:
  port: 8081
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
