spring:
  application:
    name: wallet
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: homates.exchange
    queue: homates.wallet.queue
    routingkey: homates.wallet

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    prefer-ip-address: true
