spring:
  application:
    name: shopping-list
  rabbitmq:
    host: rabbitmq
    password: admin
    port: 15672
    username: admin
    exchange: homates.exchange
    queue: homates.shopl.queue
    routingkey: homates.shopl

server:
  port: 8082
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
